:toc:

= snippy
A simple posix compliant cli snippets manager

== Usage
----
snippy v1.0
USAGE:
	snippy [-lendpUcvh] [snippet]
OPTIONS:
	-l	List all exiting snippets
	-e	Edit snippet
	-n	Creates new snippet
	-d	Delete snippet
	-p	Preview snippet
	-U	Updates  (Requires git)
	-c	Copy snippet content
	-v	Prints  version
	-h	Prints this help menu
----

== Installion
Installation is as simple as
[source,bash]
----
git clone git@github.com:viruscmd/snippy.git
cd snippy
ln -s $(pwd)/snippy.sh /usr/local/bin/snippy
----

=== Upgrading
To upgrade just perform a `git pull` or run `snippy -U`

== Configuration, Features, & Additional Recommendations
=== Configuration
There are several configurations options that can be set as env varibles in your `.bashrc` or `.zshrc`.

`$SNIPPYFILES` is the directory you wish to store your snippets. ***Default `$HOME/.snippy`***

`$SNIPPYEDITOR` is the editor you wish to edit and create snippets in. ***Default `$EDITOR`***

TIP: You can also use a visual editor like VS Code by setting `$SNIPPYEDITOR` to `$VISUAL` or `$(which code)`

`$SNIPPYCATCMD` the version of cat to use when previewing snippets. ***Default `cat` or `bat`(if it is installed)***

TIP: Other alternatives are `less`, `bat`, `vim`, etc

=== Features
Preview with syntax highlighting. This relies on link:https://github.com/sharkdp/bat[bat] *(A cat(1) clone with wings.)*.

TIP: For this to work you need to make sure you added the proper extension to your snippets

If you do have bat installed and wish to over ride it be sure to set the `$SNIPPYCATCMD` env varible

You can copy snippets to clipbpard

TIP: This is currently Mac OS only

=== Recommendations

If you wish to make your snippet portable it is best to store them in a git repo or in a drop box.

This can be accoumplished by creating a symlink to your git repo 
[source,bash]
----
ln -s /path/to/repo $HOME/.snippy
----

or by adding your repo as an env varible to your `.bashrc` or `.zshrc`
[source,bash]
----
export SNIPPYFILES="/path/to/repo"
----

If you are using `git` you will need to add, commit, and push your changes. Consider using a `cron` job to automate this.
----
*/5 * * * * ( cd /path/to/repo && git pull && git add -A && git commit -am wip && git push) 2>&1  > /dev/null
----

TIP: Please note this is an oversimplified example and might not be the right cron job for you.

== TODOs
* [ ] linux copy support
* [ ] git detection and syncing
* [ ] bash completion
* [ ] zsh completion
